version: "3.8"

services:
  database:
    build: ./database
    container_name: db_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    volumes:
      - db_volumes:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  auth_service:
    build: ./auth
    container_name: auth_cont
    ports:
      - "5001:5001"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: library
    restart: always

  book_service:
    build: ./book
    container_name: book_cont
    ports:
      - "5002:5002"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: library
    restart: always

  borrow_service:
    build: ./borrow
    container_name: borrow_cont
    ports:
      - "5003:5003"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: library
    restart: always

  app:
    build: .
    container_name: frontend_cont
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - book_service
      - borrow_service
    environment:
      AUTH_URL: http://auth_service:5001
      BOOK_URL: http://book_service:5002
      BORROW_URL: http://borrow_service:5003
    restart: always

volumes:
  db_volumes:
